CREATE TABLE "User" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" "VARCHAR(255)" NOT NULL,
  "email" "VARCHAR(255)" UNIQUE NOT NULL
);

CREATE TABLE "Profile" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "profile_type" "VARCHAR(255)" UNIQUE NOT NULL,
  "description" TEXT
);

CREATE TABLE "ProfileUser" (
  "user_id" INTEGER NOT NULL,
  "profile_id" INTEGER NOT NULL,
  PRIMARY KEY ("user_id", "profile_id")
);

CREATE TABLE "Course" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" "VARCHAR(255)" UNIQUE NOT NULL,
  "code" "VARCHAR(50)" UNIQUE
);

CREATE TABLE "Subject" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" "VARCHAR(255)" UNIQUE NOT NULL,
  "acronym" "VARCHAR(50)" UNIQUE,
  "ects" INTEGER
);

CREATE TABLE "Edition" (
  "year" INTEGER NOT NULL,
  "semester" INTEGER NOT NULL,
  "start_date" DATE,
  "end_date" DATE,
  PRIMARY KEY ("year", "semester")
);

CREATE TABLE "SubjectEdition" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "subject_id" INTEGER NOT NULL,
  "edition_year" INTEGER NOT NULL,
  "edition_semester" INTEGER NOT NULL,
  "regente_id" INTEGER NOT NULL,
  "total_students" INTEGER NOT NULL,
  "weekly_hours_tp" INTEGER DEFAULT 0,
  "weekly_hours_p" INTEGER DEFAULT 0,
  "weekly_hours_t" INTEGER DEFAULT 0,
  "weekly_hours_lab" INTEGER DEFAULT 0
);

CREATE TABLE "CourseSubjectEdition" (
  "course_id" INTEGER NOT NULL,
  "subject_edition_id" INTEGER NOT NULL,
  "curricular_year" INTEGER NOT NULL,
  PRIMARY KEY ("course_id", "subject_edition_id")
);

CREATE TABLE "Class" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "subject_edition_id" INTEGER NOT NULL,
  "identifier" "VARCHAR(20)" NOT NULL,
  "class_type" "VARCHAR(10)" NOT NULL,
  "number_students" INTEGER NOT NULL,
  "number_per_week" INTEGER NOT NULL,
  "duration" INTEGER NOT NULL
);

CREATE TABLE "Classroom" (
  "department" INTEGER NOT NULL,
  "floor" INTEGER NOT NULL,
  "number" varchar(50) NOT NULL,
  "name" "VARCHAR(100)",
  "capacity" INTEGER NOT NULL DEFAULT 0,
  "type_id" INTEGER NOT NULL,
  PRIMARY KEY ("department", "floor", "number")
);

CREATE TABLE "ClassroomType" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" "VARCHAR(255)" UNIQUE NOT NULL,
  "description" TEXT
);

CREATE TABLE "RequestClassroomType" (
  "request_id" INTEGER NOT NULL,
  "classroom_type_id" INTEGER NOT NULL,
  "quantity" INTEGER NOT NULL,
  PRIMARY KEY ("request_id", "classroom_type_id", "quantity")
);

CREATE TABLE "Draft" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" "VARCHAR(255)" NOT NULL,
  "edition_year" INTEGER NOT NULL,
  "edition_semester" INTEGER NOT NULL,
  "status" "VARCHAR(50)" NOT NULL DEFAULT 'draft',
  "created_at" TIMESTAMP NOT NULL DEFAULT (now()),
  "last_modified" TIMESTAMP NOT NULL DEFAULT (now()),
  "notes" TEXT,
  "created_by" INTEGER NOT NULL
);

CREATE TABLE "DraftClassSchedule" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "draft_id" INTEGER NOT NULL,
  "class_id" INTEGER NOT NULL,
  "teacher_id" INTEGER NOT NULL,
  "classroom_department" INTEGER NOT NULL,
  "classroom_floor" INTEGER NOT NULL,
  "classroom_number" INTEGER NOT NULL,
  "day_of_week" INTEGER NOT NULL,
  "hour_start" "TIME(0)" NOT NULL
);

CREATE TABLE "Request" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_id" INTEGER NOT NULL,
  "name" varchar(50),
  "request_date" DATE NOT NULL,
  "hour_start" "TIME(0)" NOT NULL,
  "duration" "TIME(0)" NOT NULL,
  "status_id" INTEGER NOT NULL,
  "description" TEXT,
  "number_vigilants" INTEGER,
  "created_at" TIMESTAMP NOT NULL DEFAULT (now()),
  "approved_at" TIMESTAMP,
  "approved_by" INTEGER,
  "type_request_id" INTEGER
);

CREATE TABLE "Vigilants" (
  "request_id" INTEGER NOT NULL,
  "user_id" INTEGER NOT NULL
);

CREATE TABLE "Status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar(50)
);

CREATE TABLE "TypeRequest" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar(50)
);

CREATE TABLE "RequestClassroom" (
  "request_id" INTEGER NOT NULL,
  "classroom_department" INTEGER NOT NULL,
  "classroom_floor" INTEGER NOT NULL,
  "classroom_number" INTEGER NOT NULL,
  PRIMARY KEY ("request_id", "classroom_department", "classroom_floor", "classroom_number")
);

CREATE TABLE "AuditLog" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_id" INTEGER NOT NULL,
  "action" "VARCHAR(50)" NOT NULL,
  "timestamp" TIMESTAMP NOT NULL DEFAULT (now()),
  "description" TEXT
);

CREATE TABLE "Slot" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "day_of_week" INTEGER NOT NULL,
  "time_start" "TIME(0)" NOT NULL
);

CREATE TABLE "Template" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" "VARCHAR(255)" NOT NULL,
  "user_id" INTEGER NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT (now())
);

CREATE TABLE "TemplateSlot" (
  "template_id" INTEGER NOT NULL,
  "slot_id" INTEGER NOT NULL,
  PRIMARY KEY ("template_id", "slot_id")
);

CREATE UNIQUE INDEX ON "User" ("email");

CREATE UNIQUE INDEX ON "Course" ("name");

CREATE UNIQUE INDEX ON "Course" ("code");

CREATE UNIQUE INDEX ON "Subject" ("name");

CREATE UNIQUE INDEX ON "Subject" ("acronym");

CREATE UNIQUE INDEX ON "SubjectEdition" ("subject_id", "edition_year", "edition_semester");

CREATE UNIQUE INDEX ON "Class" ("subject_edition_id", "identifier");

CREATE UNIQUE INDEX ON "ClassroomType" ("name");

CREATE UNIQUE INDEX ON "RequestClassroomType" ("request_id", "classroom_type_id");

CREATE UNIQUE INDEX ON "Draft" ("edition_year", "edition_semester", "name");

CREATE UNIQUE INDEX ON "DraftClassSchedule" ("draft_id", "class_id");

CREATE INDEX ON "DraftClassSchedule" ("teacher_id", "day_of_week", "hour_start");

CREATE INDEX ON "DraftClassSchedule" ("classroom_department", "classroom_floor", "classroom_number", "day_of_week", "hour_start");

CREATE INDEX ON "AuditLog" ("user_id", "timestamp");

CREATE INDEX ON "AuditLog" ("timestamp");

CREATE UNIQUE INDEX ON "Slot" ("day_of_week", "time_start");

COMMENT ON TABLE "Subject" IS 'UC em abstrato - APENAS dados que NUNCA mudam (nome, sigla, ECTS)';

COMMENT ON TABLE "Edition" IS 'Composite PK: (year, semester). Semester should be 1 or 2';

COMMENT ON TABLE "SubjectEdition" IS 'Instância de uma UC numa edição. Regente e alunos podem mudar entre edições.';

COMMENT ON COLUMN "SubjectEdition"."weekly_hours_tp" IS 'Horas TP semanais';

COMMENT ON COLUMN "SubjectEdition"."weekly_hours_p" IS 'Horas P semanais';

COMMENT ON COLUMN "SubjectEdition"."weekly_hours_t" IS 'Horas T semanais';

COMMENT ON COLUMN "SubjectEdition"."weekly_hours_lab" IS 'Horas Lab semanais';

COMMENT ON TABLE "CourseSubjectEdition" IS 'Liga SubjectEdition a cursos. Define em que ano curricular a UC é lecionada.';

COMMENT ON COLUMN "CourseSubjectEdition"."curricular_year" IS '1º, 2º, 3º ano do curso';

COMMENT ON TABLE "Class" IS 'Turma específica. Ex: AED-TP1';

COMMENT ON COLUMN "Class"."identifier" IS 'TP1, P1, T1, etc';

COMMENT ON COLUMN "Class"."class_type" IS 'TP, P, T, PL, LAB';

COMMENT ON TABLE "Classroom" IS 'Composite PK: (department, floor, number)';

COMMENT ON TABLE "ClassroomType" IS 'Tipos: Laboratório, Anfiteatro, Normal, etc.';

COMMENT ON TABLE "Draft" IS 'Status: draft, active, archived. Só um ativo por edição';

COMMENT ON TABLE "DraftClassSchedule" IS 'Aula concreta no draft: turma + professor + sala + horário';

COMMENT ON COLUMN "DraftClassSchedule"."day_of_week" IS '1=Segunda, 7=Domingo';

COMMENT ON TABLE "Request" IS 'Status: pending, approved, rejected, completed';

COMMENT ON TABLE "RequestClassroom" IS 'Salas atribuídas. Status individual permite aprovação parcial.';

COMMENT ON TABLE "AuditLog" IS 'Log geral de ações no sistema';

COMMENT ON COLUMN "AuditLog"."action" IS 'CREATE, UPDATE, DELETE, PUBLISH, APPROVE';

COMMENT ON COLUMN "Slot"."day_of_week" IS '1=Segunda, 7=Domingo';

COMMENT ON TABLE "Template" IS 'Templates para notificações';

ALTER TABLE "Vigilants" ADD FOREIGN KEY ("request_id") REFERENCES "Request" ("id") ON DELETE CASCADE;

ALTER TABLE "Vigilants" ADD FOREIGN KEY ("user_id") REFERENCES "User" ("id") ON DELETE RESTRICT;

ALTER TABLE "RequestClassroomType" ADD FOREIGN KEY ("request_id") REFERENCES "Request" ("id") ON DELETE CASCADE;

ALTER TABLE "RequestClassroomType" ADD FOREIGN KEY ("classroom_type_id") REFERENCES "ClassroomType" ("id") ON DELETE RESTRICT;

ALTER TABLE "Request" ADD FOREIGN KEY ("status_id") REFERENCES "Status" ("id") ON DELETE RESTRICT;

ALTER TABLE "Request" ADD FOREIGN KEY ("type_request_id") REFERENCES "TypeRequest" ("id") ON DELETE RESTRICT;

ALTER TABLE "AuditLog" ADD FOREIGN KEY ("user_id") REFERENCES "User" ("id") ON DELETE RESTRICT;

ALTER TABLE "ProfileUser" ADD FOREIGN KEY ("user_id") REFERENCES "User" ("id") ON DELETE CASCADE;

ALTER TABLE "SubjectEdition" ADD FOREIGN KEY ("regente_id") REFERENCES "User" ("id") ON DELETE RESTRICT;

ALTER TABLE "DraftClassSchedule" ADD FOREIGN KEY ("teacher_id") REFERENCES "User" ("id") ON DELETE RESTRICT;

ALTER TABLE "Request" ADD FOREIGN KEY ("user_id") REFERENCES "User" ("id") ON DELETE RESTRICT;

ALTER TABLE "Template" ADD FOREIGN KEY ("user_id") REFERENCES "User" ("id") ON DELETE CASCADE;

ALTER TABLE "Draft" ADD FOREIGN KEY ("created_by") REFERENCES "User" ("id") ON DELETE RESTRICT;

ALTER TABLE "ProfileUser" ADD FOREIGN KEY ("profile_id") REFERENCES "Profile" ("id") ON DELETE CASCADE;

ALTER TABLE "SubjectEdition" ADD FOREIGN KEY ("subject_id") REFERENCES "Subject" ("id") ON DELETE CASCADE;

ALTER TABLE "SubjectEdition" ADD FOREIGN KEY ("edition_year", "edition_semester") REFERENCES "Edition" ("year", "semester") ON DELETE CASCADE;

ALTER TABLE "CourseSubjectEdition" ADD FOREIGN KEY ("course_id") REFERENCES "Course" ("id") ON DELETE CASCADE;

ALTER TABLE "CourseSubjectEdition" ADD FOREIGN KEY ("subject_edition_id") REFERENCES "SubjectEdition" ("id") ON DELETE CASCADE;

ALTER TABLE "Class" ADD FOREIGN KEY ("subject_edition_id") REFERENCES "SubjectEdition" ("id") ON DELETE CASCADE;

ALTER TABLE "DraftClassSchedule" ADD FOREIGN KEY ("class_id") REFERENCES "Class" ("id") ON DELETE RESTRICT;

ALTER TABLE "Classroom" ADD FOREIGN KEY ("type_id") REFERENCES "ClassroomType" ("id") ON DELETE RESTRICT;

ALTER TABLE "DraftClassSchedule" ADD FOREIGN KEY ("classroom_department", "classroom_floor", "classroom_number") REFERENCES "Classroom" ("department", "floor", "number") ON DELETE RESTRICT;

ALTER TABLE "RequestClassroom" ADD FOREIGN KEY ("classroom_department", "classroom_floor", "classroom_number") REFERENCES "Classroom" ("department", "floor", "number") ON DELETE RESTRICT;

ALTER TABLE "Draft" ADD FOREIGN KEY ("edition_year", "edition_semester") REFERENCES "Edition" ("year", "semester") ON DELETE RESTRICT;

ALTER TABLE "DraftClassSchedule" ADD FOREIGN KEY ("draft_id") REFERENCES "Draft" ("id") ON DELETE CASCADE;

ALTER TABLE "RequestClassroom" ADD FOREIGN KEY ("request_id") REFERENCES "Request" ("id") ON DELETE CASCADE;

ALTER TABLE "TemplateSlot" ADD FOREIGN KEY ("template_id") REFERENCES "Template" ("id") ON DELETE CASCADE;

ALTER TABLE "TemplateSlot" ADD FOREIGN KEY ("slot_id") REFERENCES "Slot" ("id") ON DELETE CASCADE;
